ALTER TABLE CAR_SPOT DROP CONSTRAINT car_spot_fkey1;
ALTER TABLE CAR_SPOT DROP CONSTRAINT car_spot_fkey2;
ALTER TABLE CAR ALTER COLUMN id TYPE UUID USING id::uuid;
ALTER TABLE PARKING_SPOT ALTER COLUMN id TYPE UUID USING id::uuid;
ALTER TABLE CAR_SPOT ALTER COLUMN car_id TYPE UUID USING car_id::uuid;
ALTER TABLE CAR_SPOT ALTER COLUMN parking_spot_id TYPE UUID USING parking_spot_id::uuid;
ALTER TABLE CAR_SPOT ADD CONSTRAINT car_spot_fkey1 FOREIGN KEY (car_id) REFERENCES CAR(id);
ALTER TABLE CAR_SPOT ADD CONSTRAINT car_spot_fkey2 FOREIGN KEY (parking_spot_id) REFERENCES PARKING_SPOT(id);